version: "2"

linters:
  enable:
    - funlen
    - gocyclo
    - lll
  settings:
    funlen:
      lines: 60
      statements: 40
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 120
