version: 2

builds:
  - main: ./cmd/atm
    binary: atm
    env:
      - CGO_ENABLED=0
    targets:
      - darwin_arm64
      - darwin_amd64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt
